In [1]:
import numpy as np

### 1. Create a one-dimensional array (vector) with the first 10 natural numbers and output its value.

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### 2. Create a 3x3 two-dimensional array (matrix), fill it with zeros, and output its values.

In [3]:
b = np.zeros((3,3), dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### 3. Create a 5x5 array, fill it with random integers from 1 to 10, and output its value.

In [4]:
c = np.random.randint(1, 11, size=(5, 5))
print(c)

[[10 10  2  1  1]
 [ 7  2  3  2  3]
 [ 6  5  2  7  7]
 [ 8  3  6  8  7]
 [ 5  5  4  2  5]]


### 4. Create a 4x4 array, fill it with random real numbers in the range 0 to 1, and output its value.

In [5]:
d = np.random.random((4, 4))
print(d)

[[0.63822372 0.78870187 0.29459239 0.45059004]
 [0.84238633 0.09328345 0.74038004 0.57383108]
 [0.38620741 0.67286978 0.91492072 0.92954499]
 [0.26230732 0.72485646 0.88727043 0.25553495]]


### 5. Create two one-dimensional arrays of size 5, fill them with random integers in the range 1 to 10, and perform element-by-element addition, subtraction, and multiplication operations on them.

In [6]:
e = np.random.randint(1, 11, size=5)
f = np.random.randint(1, 11, size=5)
print(e)
print(f)
print(e+f)
print(e-f)
print(e*f)

[ 9  2  6  7 10]
[6 2 4 6 1]
[15  4 10 13 11]
[3 0 2 1 9]
[54  4 24 42 10]


### 6. Create two vectors of size 7, fill with random numbers and find their scalar product.

In [7]:
g = np.random.randint(1, 20, size=7)
h = np.random.randint(1, 20, size=7)
print(g)
print(h)
print(np.dot(g, h))

[ 1 18 14 17  9 15  2]
[15 17 15  6  8  4 15]
795


### 7. Create two matrices of size 2x2 and 2x3, fill them with random integers between 1 and 10, and multiply them together.

In [8]:
i = np.random.randint(1, 11, size=(2, 2))
j = np.random.randint(1, 11, size=(2, 3))
print(i)
print(j)
print(np.dot(i, j))

[[6 4]
 [4 9]]
[[ 4  3  4]
 [10  8  8]]
[[ 64  50  56]
 [106  84  88]]


### 8. Create a 3x3 matrix, fill it with random integers from 1 to 10, and find its inverse.

In [9]:
k = np.random.randint(1, 11, size=(3, 3))
print(k)
print(np.linalg.inv(k))

[[3 5 1]
 [7 2 3]
 [1 4 7]]
[[-0.01010101  0.15656566 -0.06565657]
 [ 0.23232323 -0.1010101   0.01010101]
 [-0.13131313  0.03535354  0.14646465]]


### 9. Create a 4x4 matrix, fill it with random real numbers between 0 and 1, and transpose it.

In [10]:
l = np.random.random((4, 4))
print(l)
print(l.T)

[[0.10780255 0.2680585  0.40913266 0.02591537]
 [0.774865   0.19616881 0.73136475 0.88190692]
 [0.55261575 0.32618593 0.22662199 0.88397652]
 [0.37777927 0.01984496 0.04916404 0.46941633]]
[[0.10780255 0.774865   0.55261575 0.37777927]
 [0.2680585  0.19616881 0.32618593 0.01984496]
 [0.40913266 0.73136475 0.22662199 0.04916404]
 [0.02591537 0.88190692 0.88397652 0.46941633]]


### 10. Create a 3x4 matrix and a vector of size 4, fill them with random integers between 1 and 10, and multiply the matrix by the vector.

In [11]:
m = np.random.randint(1, 11, size=(3, 4))
n = np.random.randint(1, 11, size=4)
print(m)
print(n)
print(np.dot(m, n))
print(m*n)

[[ 6 10  6  3]
 [ 8  2  1  6]
 [ 6  7  4  4]]
[ 1  7 10  7]
[157  74 123]
[[ 6 70 60 21]
 [ 8 14 10 42]
 [ 6 49 40 28]]


### 11. Create a 2x3 matrix and a vector of size 3, fill them with random real numbers between 0 and 1, and multiply the matrix by the vector.

In [12]:
o = np.random.random((2, 3))
p = np.random.random(3)
print(o)
print(p)
print(np.dot(o, p))
print(o*p)

[[0.41981413 0.412778   0.98796322]
 [0.89779137 0.14773724 0.91884292]]
[0.67917056 0.86272767 0.76897086]
[1.40095532 1.4437739 ]
[[0.2851254  0.356115   0.75971492]
 [0.60975347 0.127457   0.70656343]]


### 12. Create two 2x2 matrices, fill them with random integers between 1 and 10, and multiply them elementwise.

In [13]:
q = np.random.randint(1, 11, size=(2, 2))
r = np.random.randint(1, 11, size=(2, 2))
print(q)
print(r)
print(q*r)

[[8 6]
 [6 5]]
[[8 3]
 [7 4]]
[[64 18]
 [42 20]]


### 13. Create two 2x2 matrices, fill them with random integers from 1 to 10, and find their product.

In [14]:
s = np.random.randint(1, 11, size=(2, 2))
t = np.random.randint(1, 11, size=(2, 2))
print(s)
print(t)
print(np.dot(s, t))

[[3 3]
 [4 6]]
[[2 2]
 [2 7]]
[[12 27]
 [20 50]]


### 14. Create a 5x5 matrix, fill it with random integers from 1 to 100, and find the sum of the matrix elements.

In [15]:
u = np.random.randint(1, 101, size=(5, 5))
print(u)
print(u.sum())

[[32 85 99 46 91]
 [ 2 31 84 77 91]
 [27 34 28 77 25]
 [97 67 90 89 89]
 [72 65 57  6 31]]
1492


### 15. Create two 4x4 matrices, fill them with random integers between 1 and 10, and find their difference.

In [16]:
w = np.random.randint(1, 11, size=(4, 4))
v = np.random.randint(1, 11, size=(4, 4))
print(w)
print(v)
print(w-v)

[[6 9 5 9]
 [1 2 9 3]
 [7 5 7 1]
 [6 2 3 5]]
[[ 2  8 10  9]
 [ 1  5  2  4]
 [10  3  2  6]
 [ 9 10 10  7]]
[[ 4  1 -5  0]
 [ 0 -3  7 -1]
 [-3  2  5 -5]
 [-3 -8 -7 -2]]


### 16. Create a 3x3 matrix, fill it with random real numbers in the range 0 to 1, and find a column vector containing the sum of the elements of each row of the matrix.

In [17]:
x = np.random.random((3, 3))
print(x)
print(x.sum(axis=1).reshape((3, 1)))

[[0.62297556 0.14945167 0.42368175]
 [0.10238826 0.76631668 0.85460217]
 [0.38716362 0.43703127 0.61262373]]
[[1.19610899]
 [1.72330711]
 [1.43681862]]


### 17. Create a 3x4 matrix of random integers and create a matrix of the squares of those numbers.

In [18]:
y = np.random.randint(1, 11, size=(3, 4))
print(y)
print(pow(y,2))

[[ 6  8  8  1]
 [ 6  2  6 10]
 [ 4  4  1  3]]
[[ 36  64  64   1]
 [ 36   4  36 100]
 [ 16  16   1   9]]


### 18. Create a vector of size 4, fill it with random integers between 1 and 50, and find the square root vector of those numbers.

In [19]:
z = np.random.randint(1, 51, size=4)
print(z)
print(pow(z,0.5))

[43 36 49 28]
[6.55743852 6.         7.         5.29150262]
